**Industrial Training Day-1**

Intro to numpy and arrays

In [3]:
import numpy as np
a=np.array([1,2,3])
b=np.array([3,2,1])
print(type(a))
print(a.shape)


<class 'numpy.ndarray'>
(3,)


Performing some Arithmetic Operations

In [4]:
a=np.array([[1,2,3],[3,2,1]])
b=np.array([[1,4,6],[4,2,1]])
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[2 6 9]
 [7 4 2]]
[[ 0 -2 -3]
 [-1  0  0]]
[[ 1  8 18]
 [12  4  1]]
[[1.   0.5  0.5 ]
 [0.75 1.   1.  ]]


In [ ]:
a=np.array([[1,2,3],[3,2,1]])
b=np.array([[1,4,6],[4,2,1]])
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[2 6 9]
 [7 4 2]]
[[ 0 -2 -3]
 [-1  0  0]]
[[ 1  8 18]
 [12  4  1]]
[[1.   0.5  0.5 ]
 [0.75 1.   1.  ]]


In [6]:
a=np.array([[1,2],[3,2]])
b=np.array([[1,4],[2,1]])
print(np.dot(a,b))

[[ 5  6]
 [ 7 14]]


In [7]:
a=np.array([[1,2],[3,2]])
b=np.array([[1,4],[2,1]])
print(np.cross(a,b))

[ 2 -1]


/tmp/ipykernel_3098/1148306363.py:3: DeprecationWarning: Arrays of 2-dimensional vectors are deprecated. Use arrays of 3-dimensional vectors instead. (deprecated in NumPy 2.0)
  print(np.cross(a,b))
